# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DongJia' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DongJia
  
  pod 'Then'
  pod 'SnapKit'
  pod 'Moya','12.0.1'
  pod 'HandyJSON','5.0.0-beta'
  pod 'Kingfisher'
  pod 'MJRefresh'
  pod 'Reusable' #优化 TableView/CollectionView cell重用
  pod 'UITextView+Placeholder' #TextView支持PlaceHolder
  pod 'IQKeyboardManagerSwift'
  pod 'EmptyDataSet-Swift'
  pod 'MBProgressHUD'
  pod 'TLPhotoPicker', '~> 1.8.9'
  pod 'Bugtags'
  pod 'JPush'

#  pod 'AMap3DMap'
#  pod 'AMapSearch'
  pod 'SCLAlertView' #弹窗
  pod 'JXSegmentedView' #滑动页面
  pod 'WechatOpenSDK' #微信集成
  pod 'ZLCollectionViewFlowLayout' #CollectionView多布局
  pod 'QMUIKit' #控件库

end
